# Generated by Django 6.0.3 on 2026-03-12 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community_Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quest_name', models.TextField()),
                ('labour_shortage_activities', models.JSONField()),
                ('natural_activities', models.JSONField()),
                ('local_activities', models.JSONField()),
                ('other_information', models.TextField()),
                ('region', models.TextField()),
                ('genre_tags', models.JSONField()),
                ('rewards', models.TextField()),
                ('fee', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('available_till', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.community_manager')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('preferred_time_span', models.TextField()),
                ('application_date', models.DateTimeField(auto_now=True)),
                ('approval_status', models.BooleanField()),
                ('stay_start_date', models.DateField(null=True)),
                ('stay_end_date', models.DateField(null=True)),
                ('special_note', models.TextField(null=True)),
                ('desired_tasks', models.TextField(null=True)),
                ('remarks', models.TextField(null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.quest')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('day_to_day_schedule', models.JSONField()),
                ('application_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.application')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.community_manager')),
                ('quest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.quest')),
            ],
        ),
        migrations.CreateModel(
            name='TaskProblem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.community_manager')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number_of_people', models.IntegerField()),
                ('team_info', models.JSONField()),
                ('composition', models.TextField()),
                ('expectations_for_the_platform', models.TextField()),
                ('concerns', models.TextField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='teamId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.team'),
        ),
    ]
